# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 06:03
from __future__ import unicode_literals

from django.apps import apps
from django.db import migrations, models


survey_config = apps.get_app_config('surveys')


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='field_type',
            field=models.CharField(choices=survey_config.field_type_choices, default='free_text', max_length=255),
        ),
    ]
