# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_change_percentage_display_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
