# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_userresponse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
