# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_userresponse_precise_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], help_text='For choice fields only. Enter one or more answers, separated by newlines.', size=None),
        ),
    ]
