# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_move_translation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surveyfield',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='surveyfield',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='surveyfield',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surveyfieldset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='surveyfieldset',
            name='name',
        ),
    ]
