# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_remove_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfield',
            name='important',
            field=models.BooleanField(default=False, help_text='Does this question contribute to the completion calculation?'),
        ),
    ]
